### ISSUE TITLE
Recommendation of a book from Sheikh Abdul Qadir Jilani RA

### ISSUE THREAD

**Issue by manik007n** [IMSoley/tasawwuf#1]
I saw that some books like Fifteen Letters: Khamsata 'Ashara Maktuban and A Concise Description of Jannah & Jahannam from Sheikh Abdul Qadir Jilani RA are not available. 
It would be nice if you were to add these book to this awesome project for us to read.

Yup that's it

Thank you

**Comment by IMSoley** [comment]
Thanks for the recommendation @manik007n

- A Concise Description of Jannah & Jahannam (Excerpted from: Sufficient Provision for Seekers of the Path of Truth)

Added the other one.
